### ISSUE TITLE
Device resolution problems

### ISSUE THREAD

**Issue by sidshekar** [MSOpenTech/cocos2d-x#114]
@stammen 

HI!!. I am working on v3.3 now. I have a 800x480 display phone(as you may know :) ). When I force run the game on win32 with that resolution is looks fine and when I run the game on the phone everything seems off.

**Comment by stammen** [comment]
Are you using ResolutionPolicy::SHOW_ALL for WP8?


bool AppDelegate::applicationDidFinishLaunching() {
    // initialize director
    auto director = Director::getInstance();
    auto glview = director->getOpenGLView();
    if(!glview) {
        glview = GLViewImpl::create("Cpp Empty Test");
        director->setOpenGLView(glview);
    }

    director->setOpenGLView(glview);

    // Set the design resolution
#if (CC_TARGET_PLATFORM == CC_PLATFORM_WP8)
    // a bug in DirectX 11 level9-x on the device prevents ResolutionPolicy::NO_BORDER from working correctly
    glview->setDesignResolutionSize(designResolutionSize.width, designResolutionSize.height, ResolutionPolicy::SHOW_ALL);
#else
    glview->setDesignResolutionSize(designResolutionSize.width, designResolutionSize.height, ResolutionPolicy::NO_BORDER);
#endif

**Comment by sidshekar** [comment]
No. I am not using any resolution policy.  all the resources are 800x480 the resolution of phone lumia 820. The code is open source and part of the book Learning Cocos2d-x Game Development and can be accessed here https://github.com/sidshekar/cc2dx33_wp8Game. If I run the code on win32 at that resolution everything works fine and on the device it is all cramped.

**Comment by stammen** [comment]
Windows Phone needs the resolution policy.

**Comment by sidshekar** [comment]
Oh!!! OK. Got it.:)

**Comment by jimrange** [comment]
I'm testing on a Nokia Lumina 928W with a screen size of 1280x768, 
but on launch Cocos2d-x 3.7 thinks the screen size is half that, e.g. 640x384.

My game gets the size of the screen and lays out assets in a custom layout that varies depending on screen size. So on Android and iOS I don't need to set the design resolution policy and size. So then it uses the default, which is the devices screen size and ResolutionPolicy::UNKNOWN

For some reason screen size on Windows is half the devices actual pixel size.
Is this a bug in Cocos2d-x 3.7?
On Android and iOS, the values logged below are accurate (rather than half size).

    Size designSize = glview->getDesignResolutionSize();
    Size windowSize = Director::getInstance()->getWinSize();
    Size windowSizePixels = Director::getInstance()->getWinSizeInPixels();
    Size visibleSize = Director::getInstance()->getVisibleSize();

    CCLOG("designSize:%.2f,%.2f", designSize.width, designSize.height);
    CCLOG("WinSize:%.2f,%.2f", windowSize.width, windowSize.height);
    CCLOG("windowSizePixels:%.2f,%.2f", windowSizePixels.width, windowSizePixels.height);
    CCLOG("visibleSize:%.2f,%.2f", visibleSize.width, visibleSize.height);

    glview->setDesignResolutionSize(designSize.width,
                                                         designSize.height, 
                                                         ResolutionPolicy:: SHOW_ALL );

    designSize = glview->getDesignResolutionSize();
    windowSize = Director::getInstance()->getWinSize();
    windowSizePixels = Director::getInstance()->getWinSizeInPixels();
    visibleSize = Director::getInstance()->getVisibleSize();

    CCLOG("designSize:%.2f,%.2f", designSize.width, designSize.height);
    CCLOG("WinSize:%.2f,%.2f", windowSize.width, windowSize.height);
    CCLOG("windowSizePixels:%.2f,%.2f", windowSizePixels.width, windowSizePixels.height);
    CCLOG("visibleSize:%.2f,%.2f", visibleSize.width, visibleSize.height);

Debug Log Output
designSize:640.00,384.00
WinSize:640.00,384.00
windowSizePixels:640.00,384.00
visibleSize:640.00,384.00

designSize:640.00,384.00
WinSize:640.00,384.00
windowSizePixels:640.00,384.00
visibleSize:640.00,384.00
