### ISSUE TITLE
Current language test always shows the default system language not the current one (Windows 8.1 and Windows 10)

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#169]
1. Add another Language to be used on the machine via control panel (e.g. Russian) but keep language as the default one.
2. Run cpp-tests store app on Windows 8.1 on Windows 10;
3. From the main menu go to Current Language
4. Change the keyboard layout to use Russian language

Actual result: The test still shows that the current language is English
Expected result: Russian is a supported language for cocos, should be displayed as currently selected language

Note: Even if Russian was selected as the keyboard language at the moment of launching the cpp-tests app, the Current Language test still shows English. But if Russian was set as the system default language, then the test will show Russian even if English is currently selected.

**Comment by anniruddh** [comment]
We need to decide what should be the exact behavior in this case. Currently Cocos shows the default system language irrespective of which keyboard is selected which seems reasonable. Consider the case in which system default language is Russian and keyboard selected is English, in this case it makes more sense for Cocos reporting Russian instead of English as the language. Its better to discuss in more details about the expected behavior before making any changes to the code.

**Comment by stammen** [comment]
The correct cocos2d-x behavior is to use the system setting and not the keyboard setting. We will not make any changes to the code for now. I will keep this issue open so I can revisit it in v3.8.
